version: '3'
services:
  redis:
    image: redis:alpine
    ports: 
      - 6379:6379
    environment:
      REDIS_PASSWORD: my-password
      REDIS_PORT: 6379
      REDIS_DATABASES: 16
    networks:
      - redis-network
networks:
  redis-network: